/* Autogenerated: don't edit. */
#ifndef __USEASM_UTILS_H_
#define __USEASM_UTILS_H_

static const SGX_CORE_DESC g_sUseasmCoreTable[] =
{
#if defined(SUPPORT_SGX520)
	{	/* 520 100 revision */
		SGX_CORE_ID_520,								/* eCoreType */
		100,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_23461 |
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX520_Features_Table,						/* psFeatures */
	},
	{	/* 520 111 revision */
		SGX_CORE_ID_520,								/* eCoreType */
		111,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX520_Features_Table,						/* psFeatures */
	},
	{	/* 520 head revision */
		SGX_CORE_ID_520,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX520_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX520) */
#if defined(SUPPORT_SGX530)
	{	/* 530 110 revision */
		SGX_CORE_ID_530,								/* eCoreType */
		110,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_23062 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23164 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23461 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23960 |
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
	{	/* 530 111 revision */
		SGX_CORE_ID_530,								/* eCoreType */
		111,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_23062 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23164 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23461 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23960 |
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
	{	/* 530 1111 revision */
		SGX_CORE_ID_530,								/* eCoreType */
		1111,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_23062 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23164 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23461 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23960 |
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
	{	/* 530 120 revision */
		SGX_CORE_ID_530,								/* eCoreType */
		120,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
	{	/* 530 121 revision */
		SGX_CORE_ID_530,								/* eCoreType */
		121,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
	{	/* 530 125 revision */
		SGX_CORE_ID_530,								/* eCoreType */
		125,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
	{	/* 530 130 revision */
		SGX_CORE_ID_530,								/* eCoreType */
		130,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
	{	/* 530 head revision */
		SGX_CORE_ID_530,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX530_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX530) */
#if defined(SUPPORT_SGX531)
	{	/* 531 101 revision */
		SGX_CORE_ID_531,								/* eCoreType */
		101,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27723 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX531_Features_Table,						/* psFeatures */
	},
	{	/* 531 110 revision */
		SGX_CORE_ID_531,								/* eCoreType */
		110,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_27723,
		},
		&g_sSGX531_Features_Table,						/* psFeatures */
	},
	{	/* 531 head revision */
		SGX_CORE_ID_531,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX531_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX531) */
#if defined(SUPPORT_SGX535)
	{	/* 535 112 revision */
		SGX_CORE_ID_535,								/* eCoreType */
		112,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_23062 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23164 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23461 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23960 |
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25355 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX535_Features_Table,						/* psFeatures */
	},
	{	/* 535 113 revision */
		SGX_CORE_ID_535,								/* eCoreType */
		113,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_23461 |
			SGX_BUG_FLAGS_FIX_HW_BRN_23960 |
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25355 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX535_Features_Table,						/* psFeatures */
	},
	{	/* 535 121 revision */
		SGX_CORE_ID_535,								/* eCoreType */
		121,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_23960 |
			SGX_BUG_FLAGS_FIX_HW_BRN_24895 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25060 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25355 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX535_Features_Table,						/* psFeatures */
	},
	{	/* 535 126 revision */
		SGX_CORE_ID_535,								/* eCoreType */
		126,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX535_Features_Table,						/* psFeatures */
	},
	{	/* 535 head revision */
		SGX_CORE_ID_535,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX535_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX535) */
#if defined(SUPPORT_SGX540)
	{	/* 540 101 revision */
		SGX_CORE_ID_540,								/* eCoreType */
		101,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_25580 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25582 |
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27723 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX540_Features_Table,						/* psFeatures */
	},
	{	/* 540 110 revision */
		SGX_CORE_ID_540,								/* eCoreType */
		110,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_25804 |
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27723 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX540_Features_Table,						/* psFeatures */
	},
	{	/* 540 120 revision */
		SGX_CORE_ID_540,								/* eCoreType */
		120,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27723 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX540_Features_Table,						/* psFeatures */
	},
	{	/* 540 121 revision */
		SGX_CORE_ID_540,								/* eCoreType */
		121,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_26681 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27235 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27723 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984,
		},
		&g_sSGX540_Features_Table,						/* psFeatures */
	},
	{	/* 540 130 revision */
		SGX_CORE_ID_540,								/* eCoreType */
		130,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_27723,
		},
		&g_sSGX540_Features_Table,						/* psFeatures */
	},
	{	/* 540 head revision */
		SGX_CORE_ID_540,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX540_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX540) */
#if defined(SUPPORT_SGX541)
	{	/* 541 100 revision */
		SGX_CORE_ID_541,								/* eCoreType */
		100,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_27723 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984 |
			SGX_BUG_FLAGS_FIX_HW_BRN_28033,
		},
		&g_sSGX541_Features_Table,						/* psFeatures */
	},
	{	/* 541 head revision */
		SGX_CORE_ID_541,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX541_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX541) */
#if defined(SUPPORT_SGX543)
	{	/* 543 113 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		113,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_29643 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 117 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		117,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_29643 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 122 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		122,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_29643 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 1221 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		1221,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_29643 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 140 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		140,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 1401 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		1401,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 141 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		141,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 142 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		142,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 211 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		211,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 2111 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		2111,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 213 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		213,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 216 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		216,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 302 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		302,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 303 revision */
		SGX_CORE_ID_543,								/* eCoreType */
		303,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
	{	/* 543 head revision */
		SGX_CORE_ID_543,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX543_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX543) */
#if defined(SUPPORT_SGX544)
	{	/* 544 100 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		100,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 102 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		102,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 103 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		103,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 104 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		104,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 105 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		105,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 106 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		106,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_29643 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 110 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		110,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_29643 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30795 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30853 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30871 |
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 112 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		112,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 114 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		114,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 115 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		115,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 116 revision */
		SGX_CORE_ID_544,								/* eCoreType */
		116,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
	{	/* 544 head revision */
		SGX_CORE_ID_544,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX544_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX544) */
#if defined(SUPPORT_SGX545)
	{	/* 545 100 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		100,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_26570 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27005 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27904 |
			SGX_BUG_FLAGS_FIX_HW_BRN_27984 |
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 109 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		109,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 1011 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		1011,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 1012 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		1012,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 1013 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		1013,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 10131 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		10131,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 1014 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		1014,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 10141 revision */
		SGX_CORE_ID_545,								/* eCoreType */
		10141,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_30898 |
			SGX_BUG_FLAGS_FIX_HW_BRN_31988 |
			SGX_BUG_FLAGS_FIX_HW_BRN_33442,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
	{	/* 545 head revision */
		SGX_CORE_ID_545,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			0,
		},
		&g_sSGX545_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX545) */
#if defined(SUPPORT_SGX554)
	{	/* 554 1251 revision */
		SGX_CORE_ID_554,								/* eCoreType */
		1251,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX554_Features_Table,						/* psFeatures */
	},
	{	/* 554 head revision */
		SGX_CORE_ID_554,								/* eCoreType */
		0,											/* ui32CoreRevision */
		{												/* sBugs */
			SGX_BUG_FLAGS_FIX_HW_BRN_34293,
		},
		&g_sSGX554_Features_Table,						/* psFeatures */
	},
#endif /* defined(SUPPORT_SGX554) */
};
#endif /* __USEASM_UTILS_H_ */
