#line 2 "eurasiacon/binary2_540_omap4430_android_release/host/intermediates/pdsasmlexer/pdsasm.l.c"

#line 4 "eurasiacon/binary2_540_omap4430_android_release/host/intermediates/pdsasmlexer/pdsasm.l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[213] =
    {   0,
        0,    0,    0,    0,    0,    0,   99,   94,   93,   84,
       94,   92,   10,   70,   75,   77,   78,   73,   66,   64,
       67,   94,   71,   87,   87,   65,   86,   94,   81,   94,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   79,   80,   72,
       76,   74,   93,   94,   92,   94,   95,   96,   95,   98,
       91,   98,   98,   85,   59,   58,    1,    2,   87,   87,
       87,    0,   68,   69,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   33,    3,    4,    5,   47,   89,   89,

       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,    0,    0,    0,   90,   97,    0,   91,    0,    0,
        0,   90,   88,   88,   22,   19,   17,   89,   34,   27,
       89,   89,   89,   82,   83,   89,   89,    6,    7,   45,
       46,   89,   89,   89,   89,   31,   37,   36,   89,   89,
       29,   89,   20,   39,   40,   54,   89,   18,   89,   48,
       89,   35,   88,   88,   32,    9,    8,   28,   61,   89,
       89,   30,   41,   89,   89,   89,   11,   89,   38,   89,
       89,   89,   89,   60,   25,   26,   23,   53,   55,   52,
       51,   57,   56,   50,   49,   62,   89,   13,   14,   15,

       12,   21,   63,   89,   89,   42,   24,   16,   43,   89,
       44,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    1,    8,    1,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   24,   26,   24,   27,   28,   29,
       30,   31,    1,    1,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   38,   38,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   38,   54,
       55,    1,   56,   57,   38,    1,   58,   59,   60,   61,

       62,   63,   38,   64,   65,   38,   38,   66,   67,   68,
       69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
       38,   79,    1,   80,    1,   81,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[82] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[220] =
    {   0,
        0,   80,   80,   84,  326,   88,  325,  490,  490,  490,
      319,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,   54,   84,  102,   88,  490,  490,  286,  490,  271,
       98,   58,   74,  117,    0,   84,   99,   71,  101,  116,
       72,  162,   95,  150,  159,  155,  109,  490,  490,  490,
      490,  490,  208,  233,  234,  268,  490,  490,  266,  245,
      490,  241,  227,  490,  490,  490,  490,  490,  231,  217,
      218,  254,  490,  490,    0,  131,  171,  151,  123,  135,
      180,  211,  211,   79,  218,  222,   81,   84,  157,  213,
      224,  223,  249,    0,    0,    0,    0,    0,  226,  246,

      256,  263,  267,  262,  270,  263,  272,  268,  269,  263,
      266,  312,  226,  216,  490,  490,  194,  490,  337,  185,
      170,  490,  327,    0,    0,    0,    0,  312,    0,    0,
      276,  301,  295,    0,    0,  309,  308,    0,    0,    0,
        0,  323,  340,  136,  326,    0,    0,    0,  317,  324,
        0,  334,    0,    0,    0,    0,  325,    0,  328,    0,
      331,    0,  345,  353,    0,    0,    0,    0,    0,  397,
      343,    0,    0,  186,  129,  114,  351,  110,    0,  355,
      366,  362,  371,    0,  360,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  108,    0,    0,    0,

        0,    0,    0,  372,  378,    0,    0,    0,    0,  381,
        0,  490,  472,  475,  477,  480,  483,  486,  115
    } ;

static yyconst flex_int16_t yy_def[220] =
    {   0,
      212,    1,  213,  213,  214,  214,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  212,  212,  212,
      212,  212,  212,  212,  212,  216,  212,  212,  212,  217,
      212,  217,  218,  212,  212,  212,  212,  212,  212,  212,
      212,  219,  212,  212,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  212,  216,  216,  212,  212,  217,  212,  217,  218,
      218,  212,  219,  123,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  212,  212,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,    0,  212,  212,  212,  212,  212,  212,  212
    } ;

static yyconst flex_int16_t yy_nxt[572] =
    {   0,
        8,    9,   10,    8,   11,   12,   13,    8,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   25,   25,   25,   25,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   35,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   35,
       35,   35,   47,   35,   48,   49,   50,   31,   32,   33,
       34,   35,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   35,   35,   35,   47,   35,   51,
       52,   53,   58,   54,   59,   55,   58,   56,   59,   62,
       61,   62,   65,   62,   66,   63,   67,  134,  135,  138,

      139,   68,  140,  141,   80,   81,   69,   69,   69,   69,
       69,   69,   69,   69,   89,   86,  124,   65,   94,   66,
       69,   69,   69,   69,   69,   69,   69,   69,   70,   80,
       76,   81,   77,  208,  202,   87,  200,   71,   78,   89,
       79,   86,   70,   94,   90,   88,   99,   92,   82,  199,
       91,   71,  111,   70,   72,  178,   76,  129,   77,   93,
       83,   87,   71,   78,   84,   79,  130,   70,   85,   90,
       88,   99,  122,   92,   82,   91,   71,  111,  125,   72,
       95,   96,   97,  129,   93,   83,  100,  122,  142,   84,
      108,  103,  130,   85,  109,   98,  118,  104,  101,  105,

      128,  102,  110,  125,  126,  127,  197,  106,  107,  112,
      198,  112,  100,  112,  142,  113,  108,  103,  115,  109,
      131,   98,  104,  101,  105,  128,  102,  110,  115,  122,
      126,  127,  106,  107,  112,  112,  112,  112,  112,  112,
      113,  113,  119,  118,  119,  131,  119,  118,  120,   69,
       69,   69,   69,   69,   69,   69,   69,   70,   70,  132,
      133,  136,  137,  143,  144,  145,   71,   71,  116,  149,
      115,   70,  123,  123,  123,  123,  123,  123,  123,  123,
       71,  150,   70,   70,  132,  133,  136,  137,  143,  144,
      145,   71,   71,  146,  149,  147,   70,  148,  151,  152,

      153,   74,  154,  156,  158,   71,  157,  150,  155,  159,
      160,  161,  162,  112,   73,  112,  168,  112,  146,  113,
      147,   64,  148,  151,  212,  152,  153,  154,   61,  156,
      158,  157,  169,  155,  159,  160,  161,  162,  119,  118,
      119,  168,  119,  170,  120,  123,  123,  123,  123,  123,
      123,  123,  123,  165,  166,  171,  172,  173,  169,  174,
      179,  175,  212,  180,  176,  167,  181,  163,  170,  182,
      212,  183,  184,  185,  212,  186,  164,  196,  165,  166,
      171,  172,  201,  173,  187,  163,  179,  177,  180,  203,
      167,  181,  163,  163,  164,  182,  183,  184,  185,  204,

      186,  164,  164,  196,  205,  212,  206,  209,  201,  187,
      163,  210,  177,  207,  212,  203,  211,  212,  163,  164,
      212,  212,  212,  212,  212,  204,  212,  164,  188,  205,
      189,  190,  206,  209,  212,  212,  191,  210,  207,  212,
      192,  212,  211,  212,  193,  194,  195,  212,  212,  212,
      212,  212,  212,  212,  188,  212,  189,  190,  212,  212,
      212,  191,  212,  212,  212,  192,  212,  212,  212,  193,
      194,  195,   57,   57,   57,   60,   60,   60,   75,   75,
      114,  114,  114,  117,  117,  117,  121,  121,  121,    7,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212
    } ;

static yyconst flex_int16_t yy_chk[572] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    2,    3,    2,    4,    2,    4,    6,
        6,    6,   22,    6,   22,    6,   23,   84,   84,   87,

       87,   23,   88,   88,   32,   33,   25,   25,   25,   25,
       25,   25,   25,   25,   38,   36,  219,   22,   41,   22,
       24,   24,   24,   24,   24,   24,   24,   24,   25,   32,
       31,   33,   31,  197,  178,   37,  176,   25,   31,   38,
       31,   36,   24,   41,   39,   37,   43,   40,   34,  175,
       39,   24,   47,   25,   24,  144,   31,   79,   31,   40,
       34,   37,   25,   31,   34,   31,   80,   24,   34,   39,
       37,   43,  121,   40,   34,   39,   24,   47,   76,   24,
       42,   42,   42,   79,   40,   34,   44,  120,   89,   34,
       46,   45,   80,   34,   46,   42,  117,   45,   44,   45,

       78,   44,   46,   76,   77,   77,  174,   45,   45,   53,
      174,   53,   44,   53,   89,   53,   46,   45,  114,   46,
       81,   42,   45,   44,   45,   78,   44,   46,  113,   63,
       77,   77,   45,   45,   54,   55,   54,   55,   54,   55,
       54,   55,   62,   62,   62,   81,   62,   60,   62,   69,
       69,   69,   69,   69,   69,   69,   69,   70,   71,   82,
       83,   85,   86,   90,   91,   92,   70,   71,   59,   99,
       56,   69,   72,   72,   72,   72,   72,   72,   72,   72,
       69,  100,   70,   71,   82,   83,   85,   86,   90,   91,
       92,   70,   71,   93,   99,   93,   69,   93,  101,  102,

      103,   30,  104,  105,  107,   69,  106,  100,  104,  108,
      109,  110,  111,  112,   28,  112,  131,  112,   93,  112,
       93,   11,   93,  101,    7,  102,  103,  104,    5,  105,
      107,  106,  132,  104,  108,  109,  110,  111,  119,  119,
      119,  131,  119,  133,  119,  123,  123,  123,  123,  123,
      123,  123,  123,  128,  128,  136,  137,  142,  132,  143,
      145,  143,    0,  149,  143,  128,  150,  123,  133,  152,
        0,  157,  159,  161,    0,  161,  123,  171,  128,  128,
      136,  137,  177,  142,  161,  163,  145,  143,  149,  180,
      128,  150,  123,  164,  163,  152,  157,  159,  161,  181,

      161,  123,  164,  171,  182,    0,  183,  204,  177,  161,
      163,  205,  143,  185,    0,  180,  210,    0,  164,  163,
        0,    0,    0,    0,    0,  181,    0,  164,  170,  182,
      170,  170,  183,  204,    0,    0,  170,  205,  185,    0,
      170,    0,  210,    0,  170,  170,  170,    0,    0,    0,
        0,    0,    0,    0,  170,    0,  170,  170,    0,    0,
        0,  170,    0,    0,    0,  170,    0,    0,    0,  170,
      170,  170,  213,  213,  213,  214,  214,  214,  215,  215,
      216,  216,  216,  217,  217,  217,  218,  218,  218,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[98] =
    {   0,
       76,   77,   80,   81,   82,   83,   84,   85,   86,   88,
       91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
      101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
      111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
      121,  122,  123,  124,  127,  128,  129,  130,  131,  132,
      133,  134,  135,  136,  137,  138,  139,  142,  143,  145,
      146,  148,  149,  151,  152,  154,  155,  156,  157,  158,
      159,  160,  161,  162,  163,  164,  165,  166,  167,  168,
      169,  171,  172,  174,  175,  176,  178,  179,  180,  187,
      189,  191,  192,  194,  195,  196,  197

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "codegen/pdsasm/pdsasm.l"
#line 2 "codegen/pdsasm/pdsasm.l"
/******************************************************************************
 * Name         : pdsasm.l
 * Title        : Pixel Shader Compiler
 * Author       : John Russell
 * Created      : Jan 2002
 *
 * Copyright    : 2002-2007 by Imagination Technologies Limited.
 *              : All rights reserved. No part of this software, either
 *              : material or conceptual may be copied or distributed,
 *              : transmitted, transcribed, stored in a retrieval system or
 *              : translated into any human or computer language in any form
 *              : by any means,electronic, mechanical, manual or otherwise,
 *              : or disclosed to third parties without the express written
 *              : permission of Imagination Technologies Limited,
 *              : Home Park Estate, Kings Langley, Hertfordshire,
 *              : WD4 8LZ, U.K.
 *
 * Modifications:-
 * $Log: pdsasm.l $
 *****************************************************************************/

#include <string.h>
#include <stdlib.h>
#include <ctype.h>

#include "img_types.h"

#include "pdsasm.h"

#include "pdsasm.tab.h"

#if defined(_MSC_VER)
#pragma warning (disable:4131)
#pragma warning (disable:4127)
#pragma warning (disable:4244)
#endif /* defined(_MSC_VER) */

#define YY_SKIP_YYWRAP

static int yywrap(void)
{
	return 1;
}

int yylex(void);

extern void yyerror(const char *fmt, ...) IMG_FORMAT_PRINTF(1, 2);

static void yyeatcppcomment(void);
static void yyeatcomment(void);
static IMG_VOID ParseHashDirective(IMG_PCHAR yytext);
IMG_VOID addtoinvalidinput(IMG_CHAR c);
IMG_VOID dumpinvalidinput(IMG_VOID);

static IMG_BOOL g_bEof = IMG_FALSE;
static IMG_PCHAR g_pcSavedInvalidInput = NULL;

/*
	Returns the appropriate token when a newline is encounted. 
		(i) In C preprocessor mode the newline is ignored.
		(ii) In non-C preprocessor mode the newline is treated as delimited the end of an instruction.
*/
#define NEWLINE_TO_WHITESPACE_OR_DELIMITER	\
	if (!g_bCPreprocessor)					\
	{										\
		return SEPERATOR;		\
	}



#line 829 "eurasiacon/binary2_540_omap4430_android_release/host/intermediates/pdsasmlexer/pdsasm.l.c"

#define INITIAL 0
#define UNKNOWN_CHARACTER 1
#define IN_HEADER_FILE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 73 "codegen/pdsasm/pdsasm.l"


	/* Handle comment blocks and single line comments. */
#line 1085 "eurasiacon/binary2_540_omap4430_android_release/host/intermediates/pdsasmlexer/pdsasm.l.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 213 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 490 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 98 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 98 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 99 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "codegen/pdsasm/pdsasm.l"
{ yyeatcomment();  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "codegen/pdsasm/pdsasm.l"
{ yyeatcppcomment(); g_sCurrentLocation.uSourceLine++; NEWLINE_TO_WHITESPACE_OR_DELIMITER; }
	YY_BREAK
/* Predicates */
case 3:
YY_RULE_SETUP
#line 80 "codegen/pdsasm/pdsasm.l"
{ return P0; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "codegen/pdsasm/pdsasm.l"
{ return P1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "codegen/pdsasm/pdsasm.l"
{ return P2; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "codegen/pdsasm/pdsasm.l"
{ return IF0; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 84 "codegen/pdsasm/pdsasm.l"
{ return IF1; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 85 "codegen/pdsasm/pdsasm.l"
{ return ALUZ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "codegen/pdsasm/pdsasm.l"
{ return ALUN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 88 "codegen/pdsasm/pdsasm.l"
{ return NEG; }
	YY_BREAK
/* Opcodes */
case 11:
YY_RULE_SETUP
#line 91 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_MOVS; return OPCODE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_MOVSA; return OPCODE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_MOV16; return OPCODE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_MOV32; return OPCODE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_MOV64; return OPCODE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_MOV128; return OPCODE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_ADD; return OPCODE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_SUB; return OPCODE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_ADC; return OPCODE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_SBC; return OPCODE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_MUL; return OPCODE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_ABS; return OPCODE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_TSTZ; return OPCODE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_TSTNZ; return OPCODE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_TSTN; return OPCODE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_TSTP; return OPCODE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_BRA; return OPCODE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_CALL; return OPCODE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_RTN; return OPCODE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_HALT; return OPCODE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_NOP; return OPCODE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_ALUM; return OPCODE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_OR; return OPCODE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_AND; return OPCODE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_XOR; return OPCODE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_NOT; return OPCODE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 117 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_NOR; return OPCODE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 118 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_NAND; return OPCODE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 119 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_SHL; return OPCODE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 120 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_SHR; return OPCODE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 121 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_LOAD; return OPCODE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 122 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_STORE; return OPCODE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 123 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_RFENCE; return OPCODE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 124 "codegen/pdsasm/pdsasm.l"
{ yylval.sOpcode.sLocation = g_sCurrentLocation; yylval.sOpcode.eOpcode = PDSASM_OPCODE_RWFENCE; return OPCODE; }
	YY_BREAK
/* Register types. */
case 45:
YY_RULE_SETUP
#line 127 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_IR0; return SPECIAL_REGISTER; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_IR1; return SPECIAL_REGISTER; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_PC; return SPECIAL_REGISTER; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 130 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_TIMER; return SPECIAL_REGISTER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 131 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTU; return SPECIAL_REGISTER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTT; return SPECIAL_REGISTER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 133 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTI; return SPECIAL_REGISTER; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 134 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTD; return SPECIAL_REGISTER; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 135 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTA; return SPECIAL_REGISTER; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 136 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_SLC; return SPECIAL_REGISTER; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 137 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTC; return SPECIAL_REGISTER; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 138 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTS; return SPECIAL_REGISTER; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 139 "codegen/pdsasm/pdsasm.l"
{ yylval.eSpecialRegister = PDSASM_SPECIAL_REGISTER_DOUTO; return SPECIAL_REGISTER; }
	YY_BREAK
/* Register flags. */
case 58:
YY_RULE_SETUP
#line 142 "codegen/pdsasm/pdsasm.l"
{ return LOWFLAG; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 143 "codegen/pdsasm/pdsasm.l"
{ return HIGHFLAG; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 145 "codegen/pdsasm/pdsasm.l"
{ return CLASS_TEMP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 146 "codegen/pdsasm/pdsasm.l"
{ return CLASS_DATA; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 148 "codegen/pdsasm/pdsasm.l"
{ return TYPE_DWORD; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "codegen/pdsasm/pdsasm.l"
{ return TYPE_QWORD; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 151 "codegen/pdsasm/pdsasm.l"
{ return COMMA; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 152 "codegen/pdsasm/pdsasm.l"
{ return COLON; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 154 "codegen/pdsasm/pdsasm.l"
{ return PLUS; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 155 "codegen/pdsasm/pdsasm.l"
{ return MINUS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 156 "codegen/pdsasm/pdsasm.l"
{ return LSHIFT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 157 "codegen/pdsasm/pdsasm.l"
{ return RSHIFT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 158 "codegen/pdsasm/pdsasm.l"
{ return MODULUS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 159 "codegen/pdsasm/pdsasm.l"
{ return DIVIDE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 160 "codegen/pdsasm/pdsasm.l"
{ return XOR; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 161 "codegen/pdsasm/pdsasm.l"
{ return TIMES; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 162 "codegen/pdsasm/pdsasm.l"
{ return NOT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 163 "codegen/pdsasm/pdsasm.l"
{ return AND; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 164 "codegen/pdsasm/pdsasm.l"
{ return OR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 165 "codegen/pdsasm/pdsasm.l"
{ return OPEN_BRACKET; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 166 "codegen/pdsasm/pdsasm.l"
{ return CLOSE_BRACKET; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 167 "codegen/pdsasm/pdsasm.l"
{ return OPEN_SQUARE_BRACKET; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 168 "codegen/pdsasm/pdsasm.l"
{ return CLOSE_SQUARE_BRACKET; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 169 "codegen/pdsasm/pdsasm.l"
{ return EQUALS; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 171 "codegen/pdsasm/pdsasm.l"
{ return DATABANK0; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 172 "codegen/pdsasm/pdsasm.l"
{ return DATABANK1; }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 174 "codegen/pdsasm/pdsasm.l"
{ g_sCurrentLocation.uSourceLine++; NEWLINE_TO_WHITESPACE_OR_DELIMITER; }
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 175 "codegen/pdsasm/pdsasm.l"
{ g_sCurrentLocation.uSourceLine++; NEWLINE_TO_WHITESPACE_OR_DELIMITER; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 176 "codegen/pdsasm/pdsasm.l"
{ return SEPERATOR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 178 "codegen/pdsasm/pdsasm.l"
{ yylval.uNumber = strtoul(yytext, NULL, 10); return NUMBER; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 179 "codegen/pdsasm/pdsasm.l"
{ yylval.uNumber = strtoul(yytext, NULL, 16); return NUMBER; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 180 "codegen/pdsasm/pdsasm.l"
{ 
								yylval.sIdentifier.sLocation = g_sCurrentLocation;
								yylval.sIdentifier.pszIdentifier = _strdup(yytext);
								return IDENTIFIER; 
							}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 187 "codegen/pdsasm/pdsasm.l"
{  ParseHashDirective(yytext); return SEPERATOR; }
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 189 "codegen/pdsasm/pdsasm.l"
{ g_sCurrentLocation.uSourceLine++; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 191 "codegen/pdsasm/pdsasm.l"

	YY_BREAK
case 93:
YY_RULE_SETUP
#line 192 "codegen/pdsasm/pdsasm.l"

	YY_BREAK
case 94:
YY_RULE_SETUP
#line 194 "codegen/pdsasm/pdsasm.l"
{ BEGIN(UNKNOWN_CHARACTER); addtoinvalidinput(*yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 195 "codegen/pdsasm/pdsasm.l"
{ addtoinvalidinput(*yytext); }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 196 "codegen/pdsasm/pdsasm.l"
{ BEGIN(INITIAL); dumpinvalidinput(); return SEPERATOR; }	
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 197 "codegen/pdsasm/pdsasm.l"
{ BEGIN(INITIAL); dumpinvalidinput(); return SEPERATOR; }	
	YY_BREAK
case YY_STATE_EOF(UNKNOWN_CHARACTER):
#line 198 "codegen/pdsasm/pdsasm.l"
{ BEGIN(INITIAL); dumpinvalidinput(); return SEPERATOR; }	
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_HEADER_FILE):
#line 201 "codegen/pdsasm/pdsasm.l"
{ if (!g_bEof) { g_bEof = IMG_TRUE; NEWLINE_TO_WHITESPACE_OR_DELIMITER; } else { return -1; } }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 203 "codegen/pdsasm/pdsasm.l"
ECHO;
	YY_BREAK
#line 1713 "eurasiacon/binary2_540_omap4430_android_release/host/intermediates/pdsasmlexer/pdsasm.l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 213 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 213 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 212);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( _fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 203 "codegen/pdsasm/pdsasm.l"



IMG_VOID addtoinvalidinput(IMG_CHAR c)
{
	if (g_pcSavedInvalidInput != NULL)
	{
		int len = strlen(g_pcSavedInvalidInput);
		g_pcSavedInvalidInput = realloc(g_pcSavedInvalidInput, len + 2);
		g_pcSavedInvalidInput[len] = c;
		g_pcSavedInvalidInput[len + 1] = '\0';
	}
	else
	{
		g_pcSavedInvalidInput = malloc(2);
		g_pcSavedInvalidInput[0] = c;
		g_pcSavedInvalidInput[1] = '\0';
	}
}

IMG_VOID dumpinvalidinput(IMG_VOID)
{
	yyerror("unexpected input '%s'", g_pcSavedInvalidInput); 
	free(g_pcSavedInvalidInput);
	g_pcSavedInvalidInput = NULL;
	g_sCurrentLocation.uSourceLine++; 
}

static void yyeatcppcomment(void)
{
	char c;
	while ((c = input()) != '\n' && c != EOF); 
}

static void yyeatcomment(void)
{
	char c, c1;
	IMG_UINT32	uStartLine = g_sCurrentLocation.uSourceLine;

loop:
	while ((c = input()) != '*' && c != EOF)
	{
		if (c == '\n')
		{
			g_sCurrentLocation.uSourceLine++;
		}
	}
	if (c == EOF)
	{
		fprintf(stderr, "%s(%u): error: End of file inside comment", g_sCurrentLocation.pszSourceFile, uStartLine);
		g_bParserError = IMG_TRUE;
		return;
	}

	if ((c1 = input()) != '/' && c != EOF)
	{
		if (c1 == EOF)
		{
			fprintf(stderr, "%s(%u): error: End of file inside comment", g_sCurrentLocation.pszSourceFile, uStartLine);
			g_bParserError = IMG_TRUE;
			return;
		}
		unput(c1);
		goto loop;
	}
}

static IMG_VOID CollapseStringCodes(IMG_PCHAR pszCodes)
{
	IMG_PCHAR	pszIn, pszOut;

	pszIn = pszOut = pszCodes;
	while (*pszIn != '\0')
	{
		if (*pszIn == '\\')
		{
			pszIn++;
			*pszOut++ = *pszIn++;
		}
		else
		{
			*pszOut++ = *pszIn++;
		}
	}
	*pszOut = '\0';
}

static IMG_VOID ParseHashDirective(IMG_PCHAR yytext)
{
	char* temp = yytext + 1;
	while (isspace(*temp)) { temp++; }
	if (strncmp(temp, "line", 4) == 0 || isdigit(*temp))
    {
		if (strncmp(temp, "line", 4) == 0)
		{
			temp += 4;
			while (isspace(*temp)) { temp++; }
		}
		g_sCurrentLocation.uSourceLine = strtoul(temp, &temp, 0);
		while (isspace(*temp)) { temp++; }
		if (*temp == '"')
		{
			IMG_PCHAR	pszDot;

			char* temp2;
			temp2 = strchr(temp + 1, '"');
			if (temp2 != NULL)
			{
				IMG_PCHAR	pszSourceFile;

				pszSourceFile = malloc(temp2 - temp);
				memcpy(pszSourceFile, temp + 1, temp2 - temp - 1);
				pszSourceFile[temp2 - temp - 1] = 0;
				CollapseStringCodes(pszSourceFile);

				g_sCurrentLocation.pszSourceFile = pszSourceFile;
			}

			pszDot = strrchr(g_sCurrentLocation.pszSourceFile, '.');
			if (
					pszDot != NULL &&
					(
						strcmp(pszDot, ".h") == 0 ||
						strcmp(pszDot, ".hpp") == 0 ||
						strcmp(pszDot, ".hxx") == 0
					)
			   )
			{
				BEGIN(IN_HEADER_FILE);
			}
			else
			{
				BEGIN(INITIAL);
			}
		}
	 }
	 else
	 {
		g_sCurrentLocation.uSourceLine++; 
	 }
}

